cc_test(
    name = "serveroptions-tests",
    srcs = ["serveroptions_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@googletest//:main",
        "//src:serverlib",
    ],
)

cc_test(
    name = "handler-tests",
    srcs = ["handler_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@googletest//:main",
        "//src:serverlib",
    ],
)

cc_test(
    name = "byte-tests",
    srcs = ["byte_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@googletest//:main",
        "//src:serverlib",
    ],
)

cc_test(
    name = "msglen-tests",
    srcs = ["msglen_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@googletest//:main",
        "//src:serverlib",
    ],
)
cc_test(
    name = "type-tests",
    srcs = ["type_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@googletest//:main",
        "//src:serverlib",
    ],
)

# cc_test(
#     name = "value-tests",
#     srcs = ["value_test.cpp"],
#     copts = ["-Iexternal/gtest/include"],
#     deps = [
#         "@googletest//:main",
#         "//src:serverlib",
#     ],
# )

